export default function ShippingPolicy() {
  const paragraphs = [
    'PLEASE ALLOW 1–5 WEEKS FOR PRODUCT ARRIVAL. WE POST FREQUENT SHIPPING UPDATES (AND DELAYS IF APPLICABLE) ON OUR INSTAGRAM.',
    'WE DO OUR BEST TO SEND OUT ALL ORDERS IN A TIMELY MANNER. ONCE AN ORDER HAS BEEN PROCESSED, IT CANNOT BE MODIFIED OR CANCELED.',
    'IF YOUR ORDER IS RETURNED TO SENDER FOR ANY REASON, WE CANNOT ACCEPT RESPONSIBILITY. IF YOU NEED THE PACKAGE RESHIPPED, YOU WILL NEED TO PURCHASE A LABEL AND PROVIDE IT TO US VIA EMAIL (support@n1che.com).',
    'INTERNATIONAL CUSTOMERS MAY BE SUBJECT TO DUTIES AND FEES, WHICH ARE OUT OF OUR CONTROL. UNFORTUNATELY, WE CANNOT COVER THESE FEES AND HAVE NO WAY OF CALCULATING THE CHARGE BEFORE YOUR ORDER IS PLACED. THESE FEES WILL BE LEVIED TO YOU UPON ARRIVAL OF YOUR ORDER.',
    'PLEASE CHECK WITH YOUR LOCAL CUSTOMS OFFICE TO DETERMINE WHAT THESE ADDITIONAL COSTS WILL BE PRIOR TO YOUR PURCHASE.',
    'WE ARE NOT LIABLE FOR ANY PACKAGES THAT ARE LOST OR STOLEN DURING SHIPMENT. ONCE A PACKAGE HAS BEEN SCANNED IN BY A POSTAL PROVIDER, IT IS UNDER THEIR JURISDICTION AND IS NO LONGER OUR RESPONSIBILITY.',
    'IF YOUR PACKAGE IS MARKED AS DELIVERED BUT YOU HAVE NOT RECEIVED IT, PLEASE OPEN AN INVESTIGATION WITH YOUR CARRIER.',
  ]

  return (
    <main className="max-w-2xl mx-auto px-5 py-16">
      <h1 className="text-[11px] tracking-widest uppercase font-medium mb-12">SHIPPING POLICY</h1>

      <div className="space-y-6">
        {paragraphs.map((para, i) => (
          <div key={i}>
            <p className="text-sm leading-relaxed text-black/70">{para}</p>
            {i < paragraphs.length - 1 && <div className="border-t border-black/[0.08] mt-6" />}
          </div>
        ))}
      </div>
    </main>
  )
}
